on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Choose enviroment"
        required: true
        default: "staging"
        type: choise
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying the application."
