on:
  push:
    branches:
      - main
      - "relese/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "relese/**"
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: npm test


